name: "Default Issue Template"
description: Issueテンプレート (default)
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        ## Issueテンプレート (default)

        | 対応内容 | タイトル |
        | --- | --- |
        | 新規機能の開発 | feat(product): xyz |
        | バグの修正 | fix: xyz |
        | リファクタリング | refactor: xyz |
        | ドキュメントの追加・修正 | docs: xyz |
        | テストの追加・修正 | test: xyz |
        | その他・雑務 | chore: xyz |
  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: hogehoge
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related
      description: |
        関連するIssue, Pull Request, Discussion など

        - [ ] #1
        - [ ] #2
      placeholder: |
        - [ ] #1
        - [ ] #2
    validations:
      required: false
  - type: textarea
    id: note
    attributes:
      label: Note / TODO
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: false
